#!/bin/bash

domainxml="-"

if [ $2 == "prepare" ] || [ $2 == "start" ] || [ $2 == "stopped" ]; then
  domainXmlContents=$(cat $domainxml)
  if [ "$2" == "prepare" ]; then
    wlagent prepare-vm "'$domainXmlContents'"
  elif [ "$2" == "start" ]; then
    wlagent start-vm "'$domainXmlContents'"
  elif [ "$2" == "stopped" ]; then
    wlagent stop-vm "'$domainXmlContents'"
  fi
fi

if [ $? -ne 0 ]; then
  exit 1
fi
